Repository gorilla/websocket, pull requests merged in 2020-03, with the labels that each got.

#577 Changed the link of API references to pkg.go.dev
  README.md
Labels: documentation

#583 minor typo
  client_server_test.go
Labels: documentation

#567 Fix a couple of small typos
  example_test.go
Labels: documentation

#566 Use empty struct to protect writing
  conn.go
  prepared.go
Labels: enhancement

#563 echo example: handle received messages as text, not HTML
  examples/echo/server.go
Labels: enhancement

#570 Duration order consistency when multiplying number by time unit
  conn.go
Labels: enhancement

#568 Fix typo.
  doc.go
Labels: documentation

#584 build: clean up go.sum
  go.sum
Labels: build system
