Repository gorilla/websocket, pull requests merged in 2023-11, with the labels that each got.

#823 Fixes subprotocol selection (aling with rfc6455)
  server.go
  server_test.go
Labels: size/M

#862 Update README.md, replace master to main
  README.md
  examples/chat/README.md
Labels: size/S

#864 Use status code constant
  client.go
  proxy.go
Labels: size/XS

#865 conn.go: default close handler should not return ErrCloseSent.
  conn.go
  conn_test.go
Labels: size/S
