Repository gorilla/websocket, pull requests merged in 2024-07, with the labels that each got.

#945 Return 426 status on missing upgrade header
  client_server_test.go
  server.go
Labels: size/M

#943 Use crypto/rand for mask key
  conn.go
  prepared_test.go
Labels: size/S

#942 Improve bufio handling in Upgrader.Upgrade
  client_server_test.go
  server.go
  server_test.go
Labels: size/L

#947 Move doHandshake to client.go
  client.go
  tls_handshake.go
  tls_handshake_116.go
Labels: size/M

#932 Handle errcheck warnings
  client.go
  client_server_test.go
  compression.go
  compression_test.go
  conn.go
  conn_broadcast_test.go
  conn_test.go
  join_test.go
  prepared_test.go
  server.go
Labels: size/L

#948 Fix typos
  client_server_test.go
  conn.go
  conn_test.go
  proxy.go
Labels: size/S
