Repository gorilla/websocket, pull requests merged in 2024-06, with the labels that each got.

#926 Fixes broken random value generation
  prepared_test.go
Labels: size/XS

#929 Reverts back to v1.5.0
  .circleci/config.yml
  .editorconfig
  .github/release-drafter.yml
  .github/workflows/issues.yml
  .github/workflows/security.yml
  .github/workflows/test.yml
  .github/workflows/verify.yml
  .gitignore
  .golangci.yml
  AUTHORS
  LICENSE
  Makefile
  README.md
  client.go
  client_server_test.go
  client_test.go
  compression_test.go
  conn.go
  conn_broadcast_test.go
  conn_test.go
  example_test.go
  examples/autobahn/server.go
  examples/bufferpool/client.go
  examples/bufferpool/server.go
  examples/chat/README.md
  examples/command/main.go
  examples/echo/client.go
  examples/echo/server.go
  examples/filewatch/main.go
  go.mod
  go.sum
  join_test.go
  json_test.go
  mask_test.go
  prepared_test.go
  proxy.go
  server.go
  server_test.go
  tls_handshake.go
  util_test.go
  vendor/golang.org/x/net/LICENSE
  vendor/golang.org/x/net/PATENTS
  vendor/golang.org/x/net/internal/socks/client.go
  vendor/golang.org/x/net/internal/socks/socks.go
  vendor/golang.org/x/net/proxy/dial.go
  vendor/golang.org/x/net/proxy/direct.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/golang.org/x/net/proxy/proxy.go
  vendor/golang.org/x/net/proxy/socks5.go
  vendor/modules.txt
Labels: size/XL

#930 Set min Go version to 1.20
  .circleci/config.yml
  go.mod
Labels: size/XS

#931 Update for deprecated ioutil package
  client.go
  client_server_test.go
  compression_test.go
  conn.go
  conn_broadcast_test.go
  conn_test.go
  examples/autobahn/server.go
  examples/filewatch/main.go
Labels: size/M

#936 Improve client/server tests
  client_server_test.go
Labels: size/S

#934 Update README.md, replace master to main
  README.md
  examples/chat/README.md
Labels: size/S

#937 Silence false positive lint warning in proxy code
  proxy.go
Labels: size/S

#938 Unbundle x/net/proxy and update to recent version
  client.go
  go.mod
  go.sum
  proxy.go
  x_net_proxy.go
Labels: size/XL
